export const SPEC_TEMPLATE = (repoName: string, config: any) => `
# Functional Specifications: ${repoName}

## 🎯 Project Vision
This document outlines the core behaviors, use cases, and success criteria for the **${repoName}** mobile application, generated via the 4Gears Platform.

---

## 👥 User Personas & Use Cases

### 1. Fan (Standard User)
*Standard followers of the team/club.*
- **Onboarding**: Splash screen -> Login/Register -> Dashboard.
- **Consumption**: Browse news, match highlights, and team roster.
- **Engagement**: Access official chants, club history, and sponsor profiles.
- **Commerce**: Purchase official kit and safe-keeping digital assets in the integrated Shop.
- **Success Link**: High engagement with news and positive shop conversion.

### 2. Administrator (Club Management)
*High-level access to backend and configuration.*
- **System Monitoring**: View platform statistics (User growth, Revenue, Approval rates).
- **Content Management**: Approve/Reject submissions, manage releases, and invite new staff.
- **Commercial Management**: Manage orders and sponsor tiers.
- **Success Link**: Real-time visibility into all club operations via the Console.


### 3. Athlete (Player)
*The active core of the club.*
- **Personal Center**: View personal performance stats and training goals.
- **Logistics**: Respond to event RSVPs (Match/Training attendance).
- **Communication**: Receive direct instructions and updates from the Management.
- **Success Link**: 100% RSVP rate and improved personal performance tracking.

---

## 🛠️ Behavioral Rules & Requirements

### Access Control (RBAC)
- **Role Isolation**: Only 'Admin' personas can access the Tactics board and deep roster management.
- **Tiered Access**: 'Premium' and 'Elite' fans unlock exclusive video content and detailed match stats.

### Data Synchronization
- **Consistency**: All branding changes (Colors, Logos, Fonts) made in the 4Gears Builder must reflect instantly in the app using the \`config.json\` file.
- **Sync Logic**: The app must perform a delta-fetch for new content (News, Events) every session start.

### Monetization
- **In-App Purchase**: Integrate RevenueCat/Stripe for tier upgrades.
- **Commission Management**: Ensure accurate commission calculation for EU/US based on DMA standards.

---

## ✅ Definition of Done (Success Metrics)

1. **Visual Fidelity**: The app branding matches the 4Gears Builder configuration with 0 pixel drift.
2. **Performance**: Splash-to-Dashboard transition in under 1.5 seconds on standard devices.
3. **Robustness**: 100% functionality of the Athlete Dashboard regardless of offline state (Cached data).
4. **Security**: Role-based routing prevents unauthorized access to Admin panels.

---
*Generated by 4Gears 🤖*
`;
